version: '3'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: hdb
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  test_pg:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"