"""add assoc orm table Stock Production Product

Revision ID: ae047e36ef3f
Revises: 4e207ff792f6
Create Date: 2024-06-06 17:50:20.201391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae047e36ef3f'
down_revision: Union[str, None] = '4e207ff792f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productproductionstockassociateds',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'production_id', 'stock_id', 'id')
    )
    op.drop_table('products_productions_stocks_associated')
    op.drop_table('products_products_associated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_products_associated',
    sa.Column('poroduct_targer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('losses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poroduct_targer_id'], ['products.id'], name='products_products_associated_poroduct_targer_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='products_products_associated_product_id_fkey'),
    sa.PrimaryKeyConstraint('poroduct_targer_id', 'product_id', name='products_products_associated_pkey')
    )
    op.create_table('products_productions_stocks_associated',
    sa.Column('products_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productions_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stocks_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['productions_id'], ['productions.id'], name='products_productions_stocks_associated_productions_id_fkey'),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], name='products_productions_stocks_associated_products_id_fkey'),
    sa.ForeignKeyConstraint(['stocks_id'], ['stocks.id'], name='products_productions_stocks_associated_stocks_id_fkey'),
    sa.PrimaryKeyConstraint('products_id', 'productions_id', 'stocks_id', name='products_productions_stocks_associated_pkey')
    )
    op.drop_table('productproductionstockassociateds')
    # ### end Alembic commands ###
