"""add field weight_product and weight_stock in Production model

Revision ID: 163475ec7c79
Revises: 048ebbf1f5f1
Create Date: 2024-05-29 14:23:11.475377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "163475ec7c79"
down_revision: Union[str, None] = "048ebbf1f5f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "productions", sa.Column("weight_product", sa.Float(), nullable=False)
    )
    op.add_column(
        "productions", sa.Column("weight_stock", sa.Float(), nullable=False)
    )
    op.create_foreign_key(
        None, "warehouses", "companys", ["company_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "warehouses", type_="foreignkey")
    op.drop_column("productions", "weight_stock")
    op.drop_column("productions", "weight_product")
    # ### end Alembic commands ###
