"""m2m table

Revision ID: 4c65d6b983d0
Revises: 4109ab086958
Create Date: 2024-05-27 10:48:03.706552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c65d6b983d0"
down_revision: Union[str, None] = "4109ab086958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_productions_stocks_associated",
        sa.Column("products_id", sa.Integer(), nullable=False),
        sa.Column("productions_id", sa.Integer(), nullable=False),
        sa.Column("stocks_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["productions_id"],
            ["productions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["products_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stocks_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("products_id", "productions_id", "stocks_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_productions_stocks_associated")
    # ### end Alembic commands ###
