"""add Warehouse

Revision ID: 048ebbf1f5f1
Revises: 4dbf55bd5b2a
Create Date: 2024-05-27 11:28:26.591652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "048ebbf1f5f1"
down_revision: Union[str, None] = "4dbf55bd5b2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("warehouses")
    # ### end Alembic commands ###
