"""delete weight_stock field in production Table

Revision ID: 0ebef0933378
Revises: ae047e36ef3f
Create Date: 2024-06-07 14:14:42.302473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ebef0933378"
down_revision: Union[str, None] = "ae047e36ef3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("productions", "weight_stock")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "productions",
        sa.Column(
            "weight_stock",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
