"""empty message

Revision ID: 9bc62e2d3b0c
Revises: 0ebef0933378
Create Date: 2024-07-08 23:32:31.358517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bc62e2d3b0c"
down_revision: Union[str, None] = "0ebef0933378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "productproductionstockassociateds_production_id_fkey",
        "productproductionstockassociateds",
        type_="foreignkey",
    )
    op.drop_column("productproductionstockassociateds", "production_id")
    op.drop_table("productions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productions",
        sa.Column(
            "address", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "weight_product",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="productions_pkey"),
        sa.UniqueConstraint("address", name="productions_address_key"),
    )
    op.add_column(
        "productproductionstockassociateds",
        sa.Column(
            "production_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "productproductionstockassociateds_production_id_fkey",
        "productproductionstockassociateds",
        "productions",
        ["production_id"],
        ["id"],
    )
    # ### end Alembic commands ###
