"""deleted recipe table and add product associated table m2m

Revision ID: 4e207ff792f6
Revises: 3d942b896c42
Create Date: 2024-06-03 13:45:12.700175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e207ff792f6"
down_revision: Union[str, None] = "3d942b896c42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_products_associated",
        sa.Column("poroduct_targer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("percent", sa.FLOAT(), nullable=False),
        sa.Column("losses", sa.FLOAT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poroduct_targer_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("poroduct_targer_id", "product_id"),
    )
    op.drop_constraint(
        "products_recipe_id_fkey", "products", type_="foreignkey"
    )
    op.drop_column("products", "recipe_id")
    op.drop_table("recipes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "recipe_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "products_recipe_id_fkey", "products", "recipes", ["recipe_id"], ["id"]
    )
    op.create_table(
        "recipes",
        sa.Column(
            "recipe",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="recipes_pkey"),
    )
    op.drop_table("products_products_associated")
    # ### end Alembic commands ###
