"""delet recipe

Revision ID: c1b8f55a4c00
Revises: 3d942b896c42
Create Date: 2024-06-03 12:44:10.675671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1b8f55a4c00"
down_revision: Union[str, None] = "3d942b896c42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    op.drop_constraint(
        "products_recipe_id_fkey", "products", type_="foreignkey"
    )
    op.drop_column("products", "recipe_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "recipe_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "products_recipe_id_fkey", "products", "recipes", ["recipe_id"], ["id"]
    )
    op.create_table(
        "recipes",
        sa.Column(
            "recipe",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="recipes_pkey"),
    )
    # ### end Alembic commands ###
